name: IllyriaRPG
version: ${project.version}
main: net.prosavage.illyriarpg.IllyriaRPG
api-version: 1.14
authors: [KingAlterIV]
description: An RPG core.
depend:
  - ChatMenuAPI

commands:
  weapon:
    description: Weapon command!
    aliases: weapons
  armor:
    description: Armor command!
    aliases: armors
